name: linting

on:
 pull_request:
    branches:
      - main

jobs:
 run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.x

      - name: Install Python dependencies
        run: pip install ruff

      - name: Run linters
        run: ruff check --fix

      - name: Format code with Ruff
        run: ruff format

      - name: Commit formatting changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Formatting has been fixed'